services:
  postgres:
    image: postgres:latest
    container_name: postgres_mod1
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: MOD1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
        - mod1
  mongodb:
    image: mongo:latest
    container_name: mongodb_mod1
    restart: on-failure
    ports:
      - "27017:27017"
    networks:
        - mod1
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch_mod1
    restart: on-failure
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
        - mod1
  graylog:
    image: graylog/graylog:7.0
    container_name: graylog_mod1
    restart: on-failure
    depends_on:
      - mongodb
      - opensearch
    environment:
      GRAYLOG_PASSWORD_SECRET: "passwordsecretsupersecure"
      GRAYLOG_ROOT_PASSWORD_SHA2: "4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb_mod1:27017/graylog"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
    ports:
        - "9000:9000"
        - "12201:12201/udp"
    networks:
        - mod1
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"      # interno para outros containers
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - mod1

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "4000:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    networks:
      - mod1
volumes:
    pgdata:
    kafka_data:
networks:
    mod1:
